name: Release (PyPI Trusted Publisher)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: pypi-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build dists (sdist + wheel)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build
        run: python -m build

      - name: Twine check (metadata sanity)
        run: python -m twine check dist/*

      - name: Upload dist/ as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    name: Publish to TestPyPI (Trusted Publisher)
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: testpypi
      url: https://test.pypi.org/project/pthbz/
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distributions to TestPyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish to PyPI (Trusted Publisher)
    needs: publish-testpypi
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
      url: https://pypi.org/project/pthbz/
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distributions to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
